import { BracketRound, Match, ScheduleItem, Team } from './types';

function createBadge(label: string, bg: string, fg = '#ffffff') {
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96">
      <defs>
        <linearGradient id="g" x1="0" x2="1" y1="0" y2="1">
          <stop offset="0%" stop-color="${bg}" stop-opacity="1"/>
          <stop offset="100%" stop-color="#121212" stop-opacity="1"/>
        </linearGradient>
      </defs>
      <circle cx="48" cy="48" r="44" fill="url(#g)" stroke="rgba(255,255,255,0.18)" stroke-width="4"/>
      <text x="48" y="56" text-anchor="middle" font-family="Inter, Arial, sans-serif" font-size="28" font-weight="700" fill="${fg}">
        ${label}
      </text>
    </svg>
  `;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

export const TEAM_ASSETS: Record<string, string> = {
  icsbk: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775186185/image_7_yhrxuq.jpg',
  icshk: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775186185/image_5_ke39o1.jpg',
  fa: 'https://res.cloudinary.com/dpgt445lg/image/upload/v1775201429/logo_-_Faith_Academy_Vanguard_1_b4ebqm.jpg',
  sph: 'https://res.cloudinary.com/dpgt445lg/image/upload/v1775384563/image_13_obe33c.png',
  yiss: 'https://res.cloudinary.com/dpgt445lg/image/upload/v1775124628/image_10_1_lbxp2p.png',
  gis: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775186184/image_8_cmg9gj.jpg',
  dalat: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775186184/image_9_evbv58.jpg',
  mac: 'https://res.cloudinary.com/dpgt445lg/image/upload/v1775201427/image_11_ymckyf.png',
};

const disRoster = [
  { id: 'dis-1', name: 'Soniya Peters', grade: '12', position: 'M', jersey: '13' },
  { id: 'dis-2', name: 'Chloe Boyd', grade: '12', position: 'GK', jersey: '1' },
  { id: 'dis-3', name: 'Anna Chand', grade: '12', position: 'D', jersey: '18' },
  { id: 'dis-4', name: 'Hannah Blacklock', grade: '11', position: 'D', jersey: '4' },
  { id: 'dis-5', name: 'Isabella Coker', grade: '11', position: 'M', jersey: '7' },
  { id: 'dis-6', name: 'Reann Lim', grade: '11', position: 'D', jersey: '16' },
  { id: 'dis-7', name: 'Yehwi Kim', grade: '11', position: 'M', jersey: '14' },
  { id: 'dis-8', name: 'Marine Vallin', grade: '10', position: 'F', jersey: '12' },
  { id: 'dis-9', name: 'Lara Vallin', grade: '10', position: 'D', jersey: '2' },
  { id: 'dis-10', name: 'MinJi Kim', grade: '10', position: 'M', jersey: '10' },
  { id: 'dis-11', name: 'Millie Krahwinkel', grade: '10', position: 'F', jersey: '15' },
  { id: 'dis-12', name: 'Olivia Bekker', grade: '10', position: 'D', jersey: '8' },
  { id: 'dis-13', name: 'Savanna Kontsas', grade: '9', position: 'M', jersey: '19' },
  { id: 'dis-14', name: 'Christina Lee', grade: '9', position: 'M', jersey: '11' },
  { id: 'dis-15', name: 'Jubilee Cipolla', grade: '9', position: 'D', jersey: '5' },
  { id: 'dis-16', name: 'Sophie Lee', grade: '9', position: 'F', jersey: '6' },
  { id: 'dis-17', name: 'Irene Jeong', grade: '8', position: 'D', jersey: '3' },
  { id: 'dis-18', name: 'Rachel Joo', grade: '8', position: 'M', jersey: '9' },
];

const faRoster = [
  { id: 'fa-1', name: 'Berlyn Abels', grade: '12', position: 'CB', jersey: '30' },
  { id: 'fa-2', name: 'Serin Chang', grade: '12', position: 'W', jersey: '2 / 5 / 99' },
  { id: 'fa-3', name: 'Bernadette Gustafson', grade: '12', position: 'W', jersey: '18' },
  { id: 'fa-4', name: 'Sky Joo', grade: '12', position: 'M', jersey: '10' },
  { id: 'fa-5', name: 'Eunchae Ko', grade: '12', position: 'D', jersey: '17' },
  { id: 'fa-6', name: 'Ela Potter', grade: '12', position: 'GK', jersey: '28' },
  { id: 'fa-7', name: 'Yamima Prout', grade: '12', position: 'W', jersey: '25' },
  { id: 'fa-8', name: 'Esther Sun', grade: '12', position: 'D', jersey: '12' },
  { id: 'fa-9', name: 'Julianna Wolf', grade: '12', position: 'M', jersey: '14' },
  { id: 'fa-10', name: 'Isa Abulencia', grade: '11', position: 'M', jersey: '6' },
  { id: 'fa-11', name: 'Eunbee Cho', grade: '11', position: 'D', jersey: '11' },
  { id: 'fa-12', name: 'Verniece Eustaquio', grade: '11', position: 'CB', jersey: '9' },
  { id: 'fa-13', name: 'Grace Whittington', grade: '11', position: 'D', jersey: '20' },
  { id: 'fa-14', name: 'Zoe Benezette', grade: '10', position: 'GK', jersey: '15' },
  { id: 'fa-15', name: 'Siya Seo', grade: '10', position: 'W', jersey: '19' },
  { id: 'fa-16', name: 'Joanne Shin', grade: '10', position: 'D', jersey: '21' },
  { id: 'fa-17', name: 'Grace Briggs', grade: '9', position: 'S', jersey: '32' },
  { id: 'fa-18', name: 'Melina Zuberbuehler', grade: '9', position: 'M', jersey: '29' },
];

const gisRoster = [
  { id: 'gis-1', name: 'Seeeun Lee', grade: '12', position: 'Midfield', jersey: '10' },
  { id: 'gis-2', name: 'Alaithia Smith', grade: '12', position: 'Midfield', jersey: '23' },
  { id: 'gis-3', name: 'Ananya Srimanut', grade: '12', position: 'Forward', jersey: '11' },
  { id: 'gis-4', name: 'Zoe Price', grade: '11', position: 'Defense', jersey: '21' },
  { id: 'gis-5', name: 'Maria Mia Entner', grade: '12', position: 'Defense', jersey: '8' },
  { id: 'gis-6', name: 'Serafina Diller', grade: '11', position: 'Defense', jersey: '14' },
  { id: 'gis-7', name: 'Ellyana Moore', grade: '11', position: 'Goal', jersey: '1' },
  { id: 'gis-8', name: 'Galilee Wood', grade: '11', position: 'Midfield', jersey: '4' },
  { id: 'gis-9', name: 'Maryn Hubbard', grade: '11', position: 'Midfield', jersey: '20' },
  { id: 'gis-10', name: 'Paige Ridgley', grade: '11', position: 'Defense', jersey: '7' },
  { id: 'gis-11', name: 'Keira Shinn', grade: '11', position: 'Forward', jersey: '19' },
  { id: 'gis-12', name: 'Amber Humphrey', grade: '10', position: 'Defense', jersey: '28' },
  { id: 'gis-13', name: 'Kaylee Couts', grade: '10', position: 'Midfield', jersey: '12' },
  { id: 'gis-14', name: 'Faith Dao', grade: '10', position: 'Defense', jersey: '13' },
  { id: 'gis-15', name: 'Sarah Lonergan', grade: '9', position: 'Midfield', jersey: '77' },
  { id: 'gis-16', name: 'Madeline Wu', grade: '9', position: 'Forward', jersey: '6' },
  { id: 'gis-17', name: 'Kalliyan Krouch', grade: '9', position: 'Defense', jersey: '22' },
  { id: 'gis-18', name: 'Naomi Geijer', grade: '9', position: 'Defense', jersey: '15' },
];

const icsbkRoster = [
  { id: 'icsbk-1', name: 'Fonda', grade: '12', position: 'G', jersey: '—' },
  { id: 'icsbk-2', name: 'Hope', grade: '10', position: 'D', jersey: '—' },
  { id: 'icsbk-3', name: 'Jubilee', grade: '10', position: 'D', jersey: '—' },
  { id: 'icsbk-4', name: 'Cadie', grade: '10', position: 'D', jersey: '—' },
  { id: 'icsbk-5', name: 'Karisa', grade: '11', position: 'MF', jersey: '—' },
  { id: 'icsbk-6', name: 'Alita', grade: '11', position: 'MF', jersey: '—' },
  { id: 'icsbk-7', name: 'Rebekah', grade: 'MS', position: 'MF', jersey: '—' },
  { id: 'icsbk-8', name: 'Mackenzie', grade: '11', position: 'W', jersey: '—' },
  { id: 'icsbk-9', name: 'Bea', grade: '11', position: 'W', jersey: '—' },
  { id: 'icsbk-10', name: 'Jaya', grade: '11', position: 'S', jersey: '—' },
  { id: 'icsbk-11', name: 'Vivi', grade: '9', position: 'S', jersey: '—' },
  { id: 'icsbk-12', name: 'Jane', grade: '12', position: 'GK', jersey: '—' },
  { id: 'icsbk-13', name: 'Joy B', grade: '11', position: 'W', jersey: '—' },
  { id: 'icsbk-14', name: 'Hadassah', grade: '10', position: 'S', jersey: '—' },
  { id: 'icsbk-15', name: 'Diya D', grade: '10', position: 'D', jersey: '—' },
  { id: 'icsbk-16', name: 'Hosanna', grade: '11', position: 'MF', jersey: '—' },
  { id: 'icsbk-17', name: 'Abby', grade: '10', position: 'MF', jersey: '—' },
  { id: 'icsbk-18', name: 'Rini', grade: '11', position: 'D', jersey: '—' },
];

const icshkRoster = [
  { id: 'icshk-1', name: 'Ava Tsui', grade: '12', position: 'D', jersey: '9' },
  { id: 'icshk-2', name: 'Hana Yip', grade: '12', position: 'D', jersey: '26' },
  { id: 'icshk-3', name: 'Christy Chow', grade: '12', position: 'D', jersey: '17' },
  { id: 'icshk-4', name: 'Natalie Yam', grade: '12', position: 'F', jersey: '16' },
  { id: 'icshk-5', name: 'Nicole Dove', grade: '12', position: 'M', jersey: '8' },
  { id: 'icshk-6', name: 'Juliana Jok', grade: '12', position: 'F', jersey: '7' },
  { id: 'icshk-7', name: 'Karen Ma', grade: '12', position: 'D', jersey: '21' },
  { id: 'icshk-8', name: 'Emmy Leung Shea', grade: '11', position: 'M', jersey: '14' },
  { id: 'icshk-9', name: 'Janice Li', grade: '11', position: 'D', jersey: '3' },
  { id: 'icshk-10', name: 'Serena Chan', grade: '11', position: 'F', jersey: '6' },
  { id: 'icshk-11', name: 'Summer Indra', grade: '11', position: 'F', jersey: '2' },
  { id: 'icshk-12', name: 'Xin En Lo', grade: '11', position: 'F', jersey: '10' },
  { id: 'icshk-13', name: 'Bethany Yick', grade: '10', position: 'M', jersey: '15' },
  { id: 'icshk-14', name: 'Coco Ngan', grade: '10', position: 'D', jersey: '25' },
  { id: 'icshk-15', name: 'Bridget Shudzeka', grade: '9', position: 'GK', jersey: '12' },
  { id: 'icshk-16', name: 'Cheyenne Lo', grade: '9', position: 'D', jersey: '20' },
  { id: 'icshk-17', name: 'Jacey Chan', grade: '8', position: 'M', jersey: '11' },
  { id: 'icshk-18', name: 'Alessi Au', grade: '8', position: 'M', jersey: '5' },
];

const macRoster = [
  { id: 'mac-1', name: 'Lindsey Braithwaite', grade: '12', position: 'RM', jersey: '12' },
  { id: 'mac-2', name: 'Kaylyn Cho', grade: '12', position: 'LB', jersey: '18' },
  { id: 'mac-3', name: 'Ellie Jobert', grade: '12', position: 'CM', jersey: '14' },
  { id: 'mac-4', name: 'Rachel Kim', grade: '12', position: 'RB', jersey: '10' },
  { id: 'mac-5', name: 'Alexis Lawler', grade: '12', position: 'CM', jersey: '5' },
  { id: 'mac-6', name: 'Katelin Messimer', grade: '12', position: 'GK', jersey: '30' },
  { id: 'mac-7', name: 'Sydney Nipper', grade: '12', position: 'RM', jersey: '9' },
  { id: 'mac-8', name: 'Emily Yeung', grade: '12', position: 'S', jersey: '13' },
  { id: 'mac-9', name: 'Hannah Hong', grade: '11', position: 'CM', jersey: '11' },
  { id: 'mac-10', name: 'Mikayla Spence', grade: '11', position: 'LM', jersey: '19' },
  { id: 'mac-11', name: 'Claire Bandy', grade: '10', position: 'S', jersey: '15' },
  { id: 'mac-12', name: 'Jelena Chiu', grade: '10', position: 'LB', jersey: '21' },
  { id: 'mac-13', name: 'Jessy Lin', grade: '10', position: 'CB', jersey: '17' },
  { id: 'mac-14', name: 'Kylea Messimer', grade: '10', position: 'CB', jersey: '24' },
  { id: 'mac-15', name: 'Maya Divinagracia', grade: '9', position: 'RB', jersey: '8' },
  { id: 'mac-16', name: 'Virginia Oliver', grade: '9', position: 'CM', jersey: '7' },
  { id: 'mac-17', name: 'Ava Spence', grade: '9', position: 'GK/RB', jersey: '16' },
  { id: 'mac-18', name: 'Mia Wei', grade: '9', position: 'R/LB', jersey: '6' },
];

const sphRoster = [
  { id: 'sph-1', name: 'Kalia Bunawan', grade: '9', position: 'GK', jersey: '26' },
  { id: 'sph-2', name: 'Sherny Lim', grade: '9', position: 'ATT', jersey: '33' },
  { id: 'sph-3', name: 'Sam Prijanto', grade: '9', position: 'DEF', jersey: '44' },
  { id: 'sph-4', name: 'Marchyie Naftanel', grade: '10', position: 'ATT', jersey: '22' },
  { id: 'sph-5', name: 'Anwyn Iles', grade: '10', position: 'DEF', jersey: '79' },
  { id: 'sph-6', name: 'Ava Kasih', grade: '10', position: 'DEF', jersey: '4' },
  { id: 'sph-7', name: 'Jillian Wongso', grade: '10', position: 'ATT', jersey: '11' },
  { id: 'sph-8', name: 'Kathleen July', grade: '10', position: 'MID', jersey: '6' },
  { id: 'sph-9', name: 'Kimberly Chiu', grade: '10', position: 'MID', jersey: '10' },
  { id: 'sph-10', name: 'Livy Lim', grade: '10', position: 'DEF', jersey: '2' },
  { id: 'sph-11', name: 'Cheryl Junaidy', grade: '11', position: 'ATT/DEF', jersey: '16' },
  { id: 'sph-12', name: 'Gwen Lee', grade: '11', position: 'GK', jersey: '1' },
  { id: 'sph-13', name: 'Malika Heil', grade: '11', position: 'MID', jersey: '8' },
  { id: 'sph-14', name: 'Allison Kimberly', grade: '11', position: 'DEF', jersey: '5' },
  { id: 'sph-15', name: 'Rachel Hartono', grade: '12', position: 'DEF', jersey: '20' },
  { id: 'sph-16', name: 'Ellsha Bachtiar', grade: '12', position: 'MID/ATT', jersey: '18' },
  { id: 'sph-17', name: 'Phoebe Chang', grade: '12', position: 'ATT', jersey: '9' },
  { id: 'sph-18', name: 'Shermaine Lim', grade: '12', position: 'DEF/MID', jersey: '3' },
];

const yissRoster = [
  { id: 'yiss-1', name: 'Claire Lee', grade: '12', position: 'Midfield', jersey: '6' },
  { id: 'yiss-2', name: 'Alissa Rho', grade: '12', position: 'Striker', jersey: '1' },
  { id: 'yiss-3', name: 'Ludia Yoo', grade: '11', position: 'Midfield', jersey: '11' },
  { id: 'yiss-4', name: 'Hannah Kim', grade: '11', position: 'Midfield', jersey: '10' },
  { id: 'yiss-5', name: 'Corinne Chon', grade: '11', position: 'Mid/Def', jersey: '8' },
  { id: 'yiss-6', name: 'Maria Yang', grade: '10', position: 'Midfield', jersey: '5' },
  { id: 'yiss-7', name: 'Sofia Young', grade: '10', position: 'Defense', jersey: '14' },
  { id: 'yiss-8', name: 'Olivia Young', grade: '10', position: 'Striker', jersey: '18' },
  { id: 'yiss-9', name: 'Lana Akiyama', grade: '10', position: 'Striker', jersey: '9' },
  { id: 'yiss-10', name: 'Jaeyoung Kim', grade: '10', position: 'Defense', jersey: '4' },
  { id: 'yiss-11', name: 'Isabella Park', grade: '10', position: 'Defense', jersey: '16' },
  { id: 'yiss-12', name: 'Isabel Clark', grade: '10', position: 'Defense', jersey: '19' },
  { id: 'yiss-13', name: 'Chloe Kim', grade: '10', position: 'Goalie', jersey: '13' },
  { id: 'yiss-14', name: 'Alexis Lim', grade: '10', position: 'Midfield', jersey: '7' },
  { id: 'yiss-15', name: 'Irene Lee', grade: '10', position: 'Mid/Def', jersey: '12' },
  { id: 'yiss-16', name: 'Chloe Ko', grade: '9', position: 'Midfield', jersey: '2' },
  { id: 'yiss-17', name: 'Bria Lee', grade: '9', position: 'Midfield', jersey: '20' },
  { id: 'yiss-18', name: 'Barkot Haile', grade: '9', position: 'Midfield', jersey: '17' },
];

export const TEAMS: Record<string, Team> = {
  icsbk: { id: 'icsbk', name: 'Global Jaya School', shortName: 'GJS', logo: TEAM_ASSETS.icsbk, accent: '#5A0F2E', country: 'Indonesia', roster: icsbkRoster, photo: 'https://images.unsplash.com/photo-1518605368461-1e1296221f8c?auto=format&fit=crop&w=800&q=80', rosterImage: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775399397/icsbkk_vwevc8.png' },
  icshk: { id: 'icshk', name: 'Jakarta Intercultural School', shortName: 'JIS', logo: TEAM_ASSETS.icshk, accent: '#F4A6B8', country: 'Indonesia', roster: icshkRoster, photo: 'https://images.unsplash.com/photo-1518605368461-1e1296221f8c?auto=format&fit=crop&w=800&q=80', rosterImage: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775399398/icshk_vz6aeu.png' },
  fa: { id: 'fa', name: 'British School Jakarta', shortName: 'BSJ', logo: TEAM_ASSETS.fa, accent: '#333333', country: 'Indonesia', roster: faRoster, photo: 'https://images.unsplash.com/photo-1518605368461-1e1296221f8c?auto=format&fit=crop&w=800&q=80', rosterImage: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775399399/FAITH_qrmguv.png' },
  sph: { id: 'sph', name: 'Sekolah Pelita Harapan', shortName: 'SPH', logo: TEAM_ASSETS.sph, accent: '#5A0F2E', country: 'Indonesia', roster: sphRoster, photo: 'https://images.unsplash.com/photo-1518605368461-1e1296221f8c?auto=format&fit=crop&w=800&q=80', rosterImage: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775399397/sph_x5kkku.png' },
  yiss: { id: 'yiss', name: 'ACS', shortName: 'ACS', logo: TEAM_ASSETS.yiss, accent: '#121212', country: 'Indonesia', roster: yissRoster, photo: 'https://images.unsplash.com/photo-1518605368461-1e1296221f8c?auto=format&fit=crop&w=800&q=80', rosterImage: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775399399/Yiss_dopybh.png' },
  gis: { id: 'gis', name: 'ACG', shortName: 'ACG', logo: TEAM_ASSETS.gis, accent: '#F4A6B8', country: 'Indonesia', roster: gisRoster, photo: 'https://images.unsplash.com/photo-1518605368461-1e1296221f8c?auto=format&fit=crop&w=800&q=80', rosterImage: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775399402/GRACE_ucfiod.png' },
  dalat: { id: 'dalat', name: 'Santa Laurensia', shortName: 'STL', logo: TEAM_ASSETS.dalat, accent: '#003366', country: 'Indonesia', roster: disRoster, photo: 'https://images.unsplash.com/photo-1518605368461-1e1296221f8c?auto=format&fit=crop&w=800&q=80', rosterImage: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775399397/DALAT_rz9lx9.png' },
  mac: { id: 'mac', name: 'AIS', shortName: 'AIS', logo: TEAM_ASSETS.mac, accent: '#006600', country: 'Indonesia', roster: macRoster, photo: 'https://images.unsplash.com/photo-1518605368461-1e1296221f8c?auto=format&fit=crop&w=800&q=80', rosterImage: 'https://res.cloudinary.com/dwvzomiwu/image/upload/q_auto/f_auto/v1775399398/mac_qm5fql.png' },
};

export const MATCHES: ScheduleItem[] = [
  // TUESDAY APRIL 7 (APR-7)
  {
    id: 'e1',
    type: 'event',
    title: 'Opening Ceremony & Dinner',
    date: '2026-04-07T18:00:00Z',
    displayDate: 'Tue 7 Apr',
    time: '18:00',
    groupDate: 'Evening Events',
    stage: 'APR-7',
    venue: 'Gym 1',
  },
  {
    id: 'e2',
    type: 'event',
    title: 'Coaches Meeting',
    date: '2026-04-07T19:30:00Z',
    displayDate: 'Tue 7 Apr',
    time: '19:30',
    groupDate: 'Evening Events',
    stage: 'APR-7',
    venue: 'J100',
  },

  // WEDNESDAY APRIL 8 (APR-8)
  {
    id: 'm1',
    type: 'match',
    homeTeam: TEAMS.icshk,
    awayTeam: TEAMS.icsbk,
    date: '2026-04-08T08:00:00Z',
    displayDate: 'Wed 8 Apr',
    time: '08:00',
    groupDate: 'Morning Matches',
    stage: 'APR-8',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Group Stage',
    homeScore: 1,
    awayScore: 1,
  },
  {
    id: 'm2',
    type: 'match',
    homeTeam: TEAMS.gis,
    awayTeam: TEAMS.fa,
    date: '2026-04-08T08:00:00Z',
    displayDate: 'Wed 8 Apr',
    time: '08:00',
    groupDate: 'Morning Matches',
    stage: 'APR-8',
    status: 'Finished',
    venue: 'Side Field',
    competitionLabel: 'Group Stage',
    homeScore: 1,
    awayScore: 0,
  },
  {
    id: 'm3',
    type: 'match',
    homeTeam: TEAMS.dalat,
    awayTeam: TEAMS.sph,
    date: '2026-04-08T09:30:00Z',
    displayDate: 'Wed 8 Apr',
    time: '09:30',
    groupDate: 'Morning Matches',
    stage: 'APR-8',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Group Stage',
    homeScore: 1,
    awayScore: 0,
  },
  {
    id: 'm4',
    type: 'match',
    homeTeam: TEAMS.mac,
    awayTeam: TEAMS.yiss,
    date: '2026-04-08T09:30:00Z',
    displayDate: 'Wed 8 Apr',
    time: '09:30',
    groupDate: 'Morning Matches',
    stage: 'APR-8',
    status: 'Finished',
    venue: 'Side Field',
    competitionLabel: 'Group Stage',
    homeScore: 3,
    awayScore: 0,
  },
  {
    id: 'e3',
    type: 'event',
    title: 'Chapel',
    date: '2026-04-08T11:45:00Z',
    displayDate: 'Wed 8 Apr',
    time: '11:45',
    groupDate: 'Midday Events',
    stage: 'APR-8',
    venue: 'Gym 1',
  },
  {
    id: 'e4',
    type: 'event',
    title: 'Lunch and Service Explanation',
    date: '2026-04-08T12:30:00Z',
    displayDate: 'Wed 8 Apr',
    time: '12:30',
    groupDate: 'Midday Events',
    stage: 'APR-8',
    venue: 'K400',
  },
  {
    id: 'e5',
    type: 'event',
    title: 'Service Activity',
    date: '2026-04-08T14:00:00Z',
    displayDate: 'Wed 8 Apr',
    time: '14:00',
    groupDate: 'Afternoon Events',
    stage: 'APR-8',
    venue: 'SPH Campus',
  },

  // THURSDAY APRIL 9 (APR-9)
  {
    id: 'm5',
    type: 'match',
    homeTeam: TEAMS.sph,
    awayTeam: TEAMS.icshk,
    date: '2026-04-09T09:30:00Z',
    displayDate: 'Thu 9 Apr',
    time: '09:30',
    groupDate: 'Morning Matches',
    stage: 'APR-9',
    status: 'Finished',
    venue: 'Side Field',
    competitionLabel: 'Group Stage',
    homeScore: 0,
    awayScore: 1,
  },
  {
    id: 'm6',
    type: 'match',
    homeTeam: TEAMS.gis,
    awayTeam: TEAMS.yiss,
    date: '2026-04-09T09:30:00Z',
    displayDate: 'Thu 9 Apr',
    time: '09:30',
    groupDate: 'Morning Matches',
    stage: 'APR-9',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Group Stage',
    homeScore: 3,
    awayScore: 0,
  },
  {
    id: 'm7',
    type: 'match',
    homeTeam: TEAMS.fa,
    awayTeam: TEAMS.mac,
    date: '2026-04-09T11:00:00Z',
    displayDate: 'Thu 9 Apr',
    time: '11:00',
    groupDate: 'Late Morning Matches',
    stage: 'APR-9',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Group Stage',
    homeScore: 3,
    awayScore: 1,
  },
  {
    id: 'm8',
    type: 'match',
    homeTeam: TEAMS.dalat,
    awayTeam: TEAMS.icsbk,
    date: '2026-04-09T11:00:00Z',
    displayDate: 'Thu 9 Apr',
    time: '11:00',
    groupDate: 'Late Morning Matches',
    stage: 'APR-9',
    status: 'Finished',
    venue: 'Side Field',
    competitionLabel: 'Group Stage',
    homeScore: 0,
    awayScore: 4,
  },
  {
    id: 'e6',
    type: 'event',
    title: 'Cultural Experience ACG',
    date: '2026-04-09T10:00:00Z',
    displayDate: 'Thu 9 Apr',
    time: '10:00',
    groupDate: 'Cultural Experiences',
    stage: 'APR-9',
    venue: 'Batik Studio',
  },
  {
    id: 'e7',
    type: 'event',
    title: 'Cultural Experience ACS',
    date: '2026-04-09T10:30:00Z',
    displayDate: 'Thu 9 Apr',
    time: '10:30',
    groupDate: 'Cultural Experiences',
    stage: 'APR-9',
    venue: 'Batik Studio',
  },
  {
    id: 'e8',
    type: 'event',
    title: 'Cultural Experience JIS',
    date: '2026-04-09T11:00:00Z',
    displayDate: 'Thu 9 Apr',
    time: '11:00',
    groupDate: 'Cultural Experiences',
    stage: 'APR-9',
    venue: 'Batik Studio',
  },
  {
    id: 'e9',
    type: 'event',
    title: 'Cultural Experience STL',
    date: '2026-04-09T11:30:00Z',
    displayDate: 'Thu 9 Apr',
    time: '11:30',
    groupDate: 'Cultural Experiences',
    stage: 'APR-9',
    venue: 'Batik Studio',
  },
  {
    id: 'e10',
    type: 'event',
    title: 'Lunch',
    date: '2026-04-09T11:30:00Z',
    displayDate: 'Thu 9 Apr',
    time: '11:30',
    groupDate: 'Midday Events',
    stage: 'APR-9',
    venue: 'K400',
  },
  {
    id: 'm9',
    type: 'match',
    homeTeam: TEAMS.icsbk,
    awayTeam: TEAMS.sph,
    date: '2026-04-09T14:30:00Z',
    displayDate: 'Thu 9 Apr',
    time: '14:30',
    groupDate: 'Afternoon Matches',
    stage: 'APR-9',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Group Stage',
    homeScore: 4,
    awayScore: 0,
  },
  {
    id: 'm10',
    type: 'match',
    homeTeam: TEAMS.fa,
    awayTeam: TEAMS.yiss,
    date: '2026-04-09T14:30:00Z',
    displayDate: 'Thu 9 Apr',
    time: '14:30',
    groupDate: 'Afternoon Matches',
    stage: 'APR-9',
    status: 'Finished',
    venue: 'Side Field',
    competitionLabel: 'Group Stage',
    homeScore: 6,
    awayScore: 0,
  },
  {
    id: 'm11',
    type: 'match',
    homeTeam: TEAMS.gis,
    awayTeam: TEAMS.mac,
    date: '2026-04-09T16:00:00Z',
    displayDate: 'Thu 9 Apr',
    time: '16:00',
    groupDate: 'Afternoon Matches',
    stage: 'APR-9',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Group Stage',
    homeScore: 0,
    awayScore: 0,
  },
  {
    id: 'm12',
    type: 'match',
    homeTeam: TEAMS.icshk,
    awayTeam: TEAMS.dalat,
    date: '2026-04-09T16:00:00Z',
    displayDate: 'Thu 9 Apr',
    time: '16:00',
    groupDate: 'Afternoon Matches',
    stage: 'APR-9',
    status: 'Finished',
    venue: 'Side Field',
    competitionLabel: 'Group Stage',
    homeScore: 4,
    awayScore: 2,
  },

  // FRIDAY APRIL 10 (APR-10)
  {
    id: 'm13',
    type: 'match',
    homeTeam: TEAMS.icsbk,
    awayTeam: TEAMS.yiss,
    date: '2026-04-10T08:00:00Z',
    displayDate: 'Fri 10 Apr',
    time: '08:00',
    groupDate: 'Morning Matches',
    stage: 'APR-10',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Game 1 (A2 v B4)',
    homeScore: 3,
    awayScore: 0,
  },
  {
    id: 'm14',
    type: 'match',
    homeTeam: TEAMS.fa,
    awayTeam: TEAMS.dalat,
    date: '2026-04-10T08:00:00Z',
    displayDate: 'Fri 10 Apr',
    time: '08:00',
    groupDate: 'Morning Matches',
    stage: 'APR-10',
    status: 'Finished',
    venue: 'Side Field',
    competitionLabel: 'Game 2 (B2 v A3)',
    homeScore: 3,
    awayScore: 1,
  },
  {
    id: 'm15',
    type: 'match',
    homeTeam: TEAMS.gis,
    awayTeam: TEAMS.sph,
    date: '2026-04-10T09:30:00Z',
    displayDate: 'Fri 10 Apr',
    time: '09:30',
    groupDate: 'Morning Matches',
    stage: 'APR-10',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Game 3 (B1 v A4)',
    homeScore: 6,
    awayScore: 0,
  },
  {
    id: 'm16',
    type: 'match',
    homeTeam: TEAMS.icshk,
    awayTeam: TEAMS.mac,
    date: '2026-04-10T09:30:00Z',
    displayDate: 'Fri 10 Apr',
    time: '09:30',
    groupDate: 'Morning Matches',
    stage: 'APR-10',
    status: 'Finished',
    venue: 'Side Field',
    competitionLabel: 'Game 4 (A1 v B3)',
    homeScore: 0,
    awayScore: 1,
  },
  {
    id: 'm17',
    type: 'match',
    homeTeam: TEAMS.icsbk,
    awayTeam: TEAMS.fa,
    date: '2026-04-10T14:30:00Z',
    displayDate: 'Fri 10 Apr',
    time: '14:30',
    groupDate: 'Afternoon Matches',
    stage: 'APR-10',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Game 5 (WG1 v WG2)',
    homeScore: 4,
    awayScore: 0,
  },
  {
    id: 'm18',
    type: 'match',
    homeTeam: TEAMS.yiss,
    awayTeam: TEAMS.dalat,
    date: '2026-04-10T14:30:00Z',
    displayDate: 'Fri 10 Apr',
    time: '14:30',
    groupDate: 'Afternoon Matches',
    stage: 'APR-10',
    status: 'Finished',
    venue: 'Side Field',
    competitionLabel: 'Game 6 (LG1 v LG2)',
    homeScore: 0,
    awayScore: 2,
  },
  {
    id: 'm19',
    type: 'match',
    homeTeam: TEAMS.gis,
    awayTeam: TEAMS.mac,
    date: '2026-04-10T16:00:00Z',
    displayDate: 'Fri 10 Apr',
    time: '16:00',
    groupDate: 'Afternoon Matches',
    stage: 'APR-10',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Game 7 (WG3 v WG4)',
    homeScore: 2,
    awayScore: 1,
  },
  {
    id: 'm20',
    type: 'match',
    homeTeam: TEAMS.sph,
    awayTeam: TEAMS.icshk,
    date: '2026-04-10T16:00:00Z',
    displayDate: 'Fri 10 Apr',
    time: '16:00',
    groupDate: 'Afternoon Matches',
    stage: 'APR-10',
    status: 'Finished',
    venue: 'Side Field',
    competitionLabel: 'Game 8 (LG3 v LG4)',
    homeScore: 0,
    awayScore: 5,
  },

  // SATURDAY APRIL 11 (APR-11)
  {
    id: 'm21',
    type: 'match',
    homeTeam: TEAMS.yiss,
    awayTeam: TEAMS.sph,
    date: '2026-04-11T08:00:00Z',
    displayDate: 'Sat 11 Apr',
    time: '08:00',
    groupDate: 'Morning Matches',
    stage: 'APR-11',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: '7th Place Game (LG6 v LG8)',
    homeScore: 0,
    awayScore: 2,
  },
  {
    id: 'm22',
    type: 'match',
    homeTeam: TEAMS.dalat,
    awayTeam: TEAMS.icshk,
    date: '2026-04-11T09:30:00Z',
    displayDate: 'Sat 11 Apr',
    time: '09:30',
    groupDate: 'Morning Matches',
    stage: 'APR-11',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: '5th Place Game (WG6 v WG8)',
    homeScore: 1,
    awayScore: 3,
  },
  {
    id: 'm23',
    type: 'match',
    homeTeam: TEAMS.fa,
    awayTeam: TEAMS.mac,
    date: '2026-04-11T11:00:00Z',
    displayDate: 'Sat 11 Apr',
    time: '11:00',
    groupDate: 'Morning Matches',
    stage: 'APR-11',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: '3rd Place Game (LG5 v LG7)',
    homeScore: 3,
    awayScore: 0,
  },
  {
    id: 'e16',
    type: 'event',
    title: 'Lunch',
    date: '2026-04-11T11:30:00Z',
    displayDate: 'Sat 11 Apr',
    time: '11:30',
    groupDate: 'Midday Events',
    stage: 'APR-11',
    venue: 'K400',
  },
  {
    id: 'm24',
    type: 'match',
    homeTeam: TEAMS.icsbk,
    awayTeam: TEAMS.gis,
    date: '2026-04-11T14:00:00Z',
    displayDate: 'Sat 11 Apr',
    time: '14:00',
    groupDate: 'Afternoon Matches',
    stage: 'APR-11',
    status: 'Finished',
    venue: 'Main Field',
    competitionLabel: 'Championship Game (WG5 v WG7)',
    homeScore: 2,
    awayScore: 0,
  },
  {
    id: 'e17',
    type: 'event',
    title: 'Coaches’ Meeting',
    date: '2026-04-11T16:30:00Z',
    displayDate: 'Sat 11 Apr',
    time: '16:30',
    groupDate: 'Evening Events',
    stage: 'APR-11',
    venue: 'J100',
  },
  {
    id: 'e18',
    type: 'event',
    title: 'Awards Ceremony and Banquet Dinner',
    date: '2026-04-11T17:30:00Z',
    displayDate: 'Sat 11 Apr',
    time: '17:30',
    groupDate: 'Evening Events',
    stage: 'APR-11',
    venue: 'Gym 1',
  }
];

export const BRACKET_DATA: BracketRound[] = [
  {
    id: 'qf',
    title: 'Quarterfinals',
    matches: [
      {
        id: 'q1',
        homeTeam: TEAMS.icsbk,
        awayTeam: TEAMS.yiss,
        dateLabel: '10 Apr, 08:00',
      },
      {
        id: 'q2',
        homeTeam: TEAMS.fa,
        awayTeam: TEAMS.dalat,
        dateLabel: '10 Apr, 08:00',
      },
      {
        id: 'q3',
        homeTeam: TEAMS.gis,
        awayTeam: TEAMS.sph,
        dateLabel: '10 Apr, 09:30',
      },
      {
        id: 'q4',
        homeTeam: TEAMS.icshk,
        awayTeam: TEAMS.mac,
        dateLabel: '10 Apr, 09:30',
      },
    ],
  },
  {
    id: 'sf',
    title: 'Semifinals',
    matches: [
      {
        id: 's1',
        homeTeamPlaceholder: 'WG1',
        awayTeamPlaceholder: 'WG2',
        dateLabel: '10 Apr, 14:30',
      },
      {
        id: 's2',
        homeTeamPlaceholder: 'WG3',
        awayTeamPlaceholder: 'WG4',
        dateLabel: '10 Apr, 16:00',
      },
    ],
  },
  {
    id: 'f',
    title: 'Finals',
    matches: [
      {
        id: 'f1',
        homeTeamPlaceholder: 'WG5',
        awayTeamPlaceholder: 'WG7',
        dateLabel: '11 Apr, 14:00',
        aggregateText: 'Championship Match',
      },
    ],
  },
];

export const HOME_FEATURED_MATCH = MATCHES.find(
  (match) => match.type === 'match' && match.status === 'Upcoming'
) as Match;
export const HOME_UPCOMING_MATCHES = MATCHES.filter(
  (match) => match.type === 'match' && match.status === 'Upcoming'
) as Match[];
export const HOME_FINISHED_MATCHES = MATCHES
  .filter((match) => match.type === 'match' && match.status === 'Finished')
  .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()) as Match[];

export const APP_COPY = {
  title: 'Asia Christian Schools Conference',
  subtitle: 'Unity • Faith • Competition',
  heroLabel: 'Next Match',
  sectionUpcoming: 'Upcoming Matches',
  sectionQuickAccess: 'Quick Access',
};
